CREATE TABLE `assinaturasSadt` (
	`id` int AUTO_INCREMENT NOT NULL,
	`guiaId` int NOT NULL,
	`pacienteId` int NOT NULL,
	`profissionalId` int NOT NULL,
	`atendimentoId` int,
	`numeroSessao` int NOT NULL DEFAULT 1,
	`dataSessao` date NOT NULL,
	`procedimento` varchar(255) NOT NULL,
	`pacienteNome` varchar(255) NOT NULL,
	`pacienteCpf` varchar(14),
	`pacienteWhatsapp` varchar(20),
	`token` varchar(128) NOT NULL,
	`tokenExpiresAt` timestamp NOT NULL,
	`status` enum('pendente','assinado','expirado','cancelado') NOT NULL DEFAULT 'pendente',
	`assinaturaDataUrl` text,
	`assinaturaHash` varchar(64),
	`ipAssinatura` varchar(45),
	`userAgentAssinatura` text,
	`dataAssinatura` timestamp,
	`whatsappEnviado` tinyint NOT NULL DEFAULT 0,
	`dataEnvioWhatsapp` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `assinaturasSadt_id` PRIMARY KEY(`id`),
	CONSTRAINT `assinaturasSadt_token_unique` UNIQUE(`token`)
);
