CREATE TABLE `bradescoAutorizacoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`guiaId` int NOT NULL,
	`pacienteId` int NOT NULL,
	`convenioId` int NOT NULL,
	`numeroCarteira` varchar(50),
	`validadeCarteira` date,
	`nomePaciente` varchar(255) NOT NULL,
	`codigoTUSS` varchar(20) NOT NULL,
	`descricaoProcedimento` varchar(255),
	`cid10` varchar(10) NOT NULL DEFAULT 'F41',
	`quantidadeSessoes` int NOT NULL DEFAULT 1,
	`dataInicio` date,
	`dataFim` date,
	`nomeMedicoSolicitante` varchar(255),
	`crmMedicoSolicitante` varchar(30),
	`ufMedicoSolicitante` varchar(2),
	`cbosMedicoSolicitante` varchar(10),
	`pedidoMedicoUrl` text,
	`pedidoMedicoNomeArquivo` varchar(255),
	`status` enum('pendente_documentacao','pendente','aguardando_acao_humana','enviado_portal','autorizado','negado','erro','cancelado') NOT NULL DEFAULT 'pendente',
	`protocoloBradesco` varchar(50),
	`numeroAutorizacaoBradesco` varchar(40),
	`senhaAutorizacaoBradesco` varchar(30),
	`dataAutorizacaoBradesco` date,
	`validadeAutorizacaoBradesco` date,
	`sessoesAutorizadas` int,
	`motivoNegacao` text,
	`logExecucao` text,
	`tentativas` int NOT NULL DEFAULT 0,
	`ultimaTentativa` timestamp,
	`solicitadoPor` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bradescoAutorizacoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bradescoCredenciais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cpfResponsavel` varchar(14) NOT NULL,
	`cnpjPrestador` varchar(18) NOT NULL,
	`nomePrestador` varchar(255),
	`senhaLogin` varchar(255) NOT NULL,
	`ativo` tinyint NOT NULL DEFAULT 1,
	`convenioId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bradescoCredenciais_id` PRIMARY KEY(`id`)
);
